syntax = "proto3";

package notification.v1;

service NotificationService {
  rpc SendConfirmation (SendConfirmationRequest) returns (SendConfirmationResponse);
  rpc SendRelease (SendReleaseRequest) returns (SendReleaseResponse);
}

message SendConfirmationRequest {
  string to = 1;
  string repo = 2;
  string confirmation_url = 3;
  string unsubscribe_url = 4;
}

message SendConfirmationResponse {
  string message = 1;
}

message SendReleaseRequest {
  string to = 1;
  string repo = 2;
  string tag = 3;
  string release_url = 4;
  string unsubscribe_url = 5;
}

message SendReleaseResponse {
  string message = 1;
}
